import type { User } from './user.types.js';

/**
 * User repository abstraction
 *
 * Defines the minimal persistence contract needed by authentication.
 * This is not a full CRUD repository - it only contains operations
 * that authentication actually requires.
 *
 * Database implementations will provide concrete implementations
 * using their chosen database technology (PostgreSQL, MongoDB, etc.)
 */

export interface UserRepository {
  /**
   * Find a user by email address
   *
   * @param email - The email to search for
   * @returns The user if found, null otherwise
   */
  findUserByEmail(email: string): Promise<User | null>;

  /**
   * Find a user by ID
   *
   * @param userId - The user ID to search for
   * @returns The user if found, null otherwise
   */
  findUserById(userId: string): Promise<User | null>;

  /**
   * Create a new user
   *
   * @param user - The user data to create (without id and createdAt, which are generated by the repository)
   * @returns The created user with id and createdAt
   */
  createUser(user: Omit<User, 'id' | 'createdAt'>): Promise<User>;
}
